# Generated by Django 4.2.15 on 2024-08-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to='uploads/%y/%m'),
        ),
    ]
