# Generated by Django 4.2.15 on 2024-09-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0003_product_discount_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
