# Generated by Django 4.2.15 on 2024-09-08 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0004_remove_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='price',
            new_name='priceTong',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='priceAll',
        ),
    ]
