# Generated by Django 4.2.15 on 2024-09-13 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0006_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='priceAll',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cartitem',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dodung.cartitem'),
        ),
    ]
