# Generated by Django 4.2.15 on 2024-09-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0007_remove_orderitem_priceall_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
