# Generated by Django 4.2.15 on 2024-09-14 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0009_order_note_alter_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
