# Generated by Django 4.2.15 on 2024-09-14 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0010_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(related_name='orders', to='dodung.cartitem'),
        ),
    ]
