# Generated by Django 4.2.15 on 2024-09-14 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0012_remove_order_order_items_cartitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='cart_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='dodung.cartitem'),
        ),
    ]
