# Generated by Django 4.2.15 on 2024-09-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0014_remove_order_cart_item_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
