# Generated by Django 4.2.15 on 2024-09-15 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0016_rename_price_orderitem_pricetong_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Tiền mặt', 'Tiền mặt'), ('Chuyển khoản ngân hàng', 'Chuyển khoản ngân hàng'), ('Thanh toán trực tuyến', 'Thanh toán trực tuyến')], default='Tiền mặt', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Đang chờ', 'Đang chờ'), ('Đã giao', 'Đã giao'), ('Đã hủy', 'Đã hủy')], max_length=20),
        ),
    ]
