# Generated by Django 4.2.15 on 2024-09-16 10:42

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0017_alter_order_payment_method_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_transfer_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagebank'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Thanh toán khi nhận hàng', 'Thanh toán khi nhận hàng'), ('Chuyển khoản ngân hàng', 'Chuyển khoản ngân hàng'), ('Thanh toán trực tuyến', 'Thanh toán trực tuyến')], default='Thanh toán khi nhận hàng', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Đang chờ', 'Đang chờ'), ('Đang giao', 'Đang giao'), ('Đã giao', 'Đã giao'), ('Đã hủy', 'Đã hủy')], max_length=20),
        ),
    ]
