# Generated by Django 4.2.15 on 2024-09-16 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0020_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Chat',
        ),
    ]
