# Generated by Django 4.2.15 on 2024-09-17 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dodung', '0021_rename_message_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
